### ISSUE TITLE
Use jpm/cgen?

### ISSUE THREAD

**Issue by AlecTroemel** [AlecTroemel/janet-chipmunk#1]
@pepe introduced cgen to me, but I'm still pretty green on how cgen works and what benefits it brings. I'll need to do some reading on the source https://github.com/janet-lang/jpm/blob/d841549a76177e68df0231c2f678590d27c0c16d/jpm/cgen.janet.. but the thought of being able to use janets macro system is **very appealing**

**Comment by pepe** [comment]
I have PRed https://github.com/janet-lang/jpm/pull/59 last improvement I have found when using cgen, so if it makes it through, I will start to help here, if you would not mind.

**Comment by pepe** [comment]
I was looking at the code you already have here, and I guess cgen would be great here.

But I may be wrong :-D.

**Comment by AlecTroemel** [comment]
@pepe I would love some help! I was planning on digging into this tomorrow (Friday 9/2). There are _a lot_ of functions like this

```c
static Janet cfun_shape_set_elasticity(int32_t argc, Janet *argv)  {
  janet_fixarity(argc, 2);
  cpShape *shape = cp_getshape(argv, 0);
  float value = janet_getnumber(argv, 1);
  cpShapeSetElasticity(shape, value);
  return janet_wrap_nil();
}
```

where I setup some args, call the chipmunk function, then return null. My gut says there's got to be a macro we could write that would compress things down to something like... 

```janet
# cgen macro (cp-setter FUNCTION_NAME ;ARG_TYPES)
(cp-setter cpShapeSetElasticity cpShape float)
```

I pulling stuff out of thin air, so I'm really open to any syntax. I just want to type less lines haha

**Comment by pepe** [comment]
That is great to hear. To taste the possibilities, today, I started to wrap notcurses and came up with https://git.sr.ht/~pepe/janet-curses-not/tree/master/item/src/notcurses.cgen#L34 with the help of https://git.sr.ht/~pepe/janet-curses-not/tree/master/item/codes.janet Indeed your use-case is very easy to implement this way.

**Comment by AlecTroemel** [comment]
@pepe feel free to start on this if want today! If you do, could you push up a branch and/or draft PR so I can pick up where you leave off tomorrow?

**Comment by pepe** [comment]
I will try, but I am afraid I cannot promise anything :-).

**Comment by pepe** [comment]
I guess this patch shows how it could be done with specialized macros https://git.sr.ht/~pepe/janet-curses-not/commit/3f06086a01b56f9882ba137c18a5873dff89380b

**Comment by pepe** [comment]
I already refactored it a little https://git.sr.ht/~pepe/janet-curses-not/commit/e1769341ce6480580496e4abcc8330754542d682

**Comment by AlecTroemel** [comment]
Closing this for now, as I've converted this project to cgen using some "first pass" macros. I'm open to any changes though!
