### ISSUE TITLE
add-loader in project.janet unknown symbol

### ISSUE THREAD

**Issue by sogaiu** [AlecTroemel/janet-chipmunk#7]
Was trying to do `jpm rules` and got the output:

```
./project.janet:8:1: compile error: unknown symbol add-loader
```

What is `add-loader` in project.janet?  Is that something from spork?

Oh wait, may be it's from cgen?

**Comment by pepe** [comment]
It is definitely cgen. I am seeing the same in gp.

**Comment by sogaiu** [comment]
@pepe Ah I see.

With the latest `jpm`, I think this won't work because `add-loader` got removed (possibly unintentionally).

I got a similar error when I tried `jpm deps` with gp.

**Comment by pepe** [comment]
Indeed. I am sure you are right.

**Comment by sogaiu** [comment]
I mentioned the removal of `add-loader` at the help channel so may be we'll get a response there about it.

**Comment by sogaiu** [comment]
Looks like it's back: https://github.com/janet-lang/jpm/commit/6771439785aea36c76c5aec7c2d7f67df83c46bb
